### ISSUE TITLE
Documentation question 

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1062]
I see there are three ways of using this awesome tool. 
1 command line
2 dbus
3 jsonrpc

when should I use which one?

I currently have a php class to interact with signal cli via 1

Is dbus or jsonrpc faster/ better?

how to descide?

**Comment by morph027** [comment]
Basically, 2 (dbus) and 3 (jsonrpc) are faster as they are running as a daemon and everything (runtime, network setup, ...) has been loaded already, which needs to be done again for every single 1 (command line) call.

I prefer jsonrpc, as it's closer to the commandline (same method calls) and is easier to setup. dbus lacks some features and is quite complex to setup. also requires dbus ;)

You need to create jsonrpc client which is using tcp within your php app.

Otherwise you could have a look at one of these projects (disclaimer: i'm the author of the second one), which are wrapping the jsonrpc into a rest api:

* https://github.com/bbernhard/signal-cli-rest-api/
* https://gitlab.com/morph027/python-signal-cli-rest-api/

I'm also about to create a plain jsonrpc - rest gateway, which just passthrough http rest calls to jsonrpc tcp connections.

**Comment by Tsjippy** [comment]
Thanks.
I still think this should be added to the documentation

**Comment by morph027** [comment]
I guess this one covers the topic quite good: https://github.com/AsamK/signal-cli/wiki/FAQ#performance
