### ISSUE TITLE
More clarity needed on when to use dbus-send

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1079]
From the docs its clear that you can use two methods to talk to `dbus: signal-cli —dbus COMMAND` or `dbus-send --session --dest=org.asamk.Signal --type=method_call --print-reply /org/asamk/Signal org.asamk.Signal.COMMAND`

Does one have a preference over the other?
My session dbus is started in multi account mode. The link account gives a cleaner output when using —dbus link

**Comment by AsamK** [comment]
That depends on your use-case. 
- `dbus-send` is a low level dbus util, that can be used to communicate with any dbus service. It's fast but cumbersome to use manually.
- `signal-cli --dbus` is a signal-cli specific dbus client that provides a nicer interface for manual use, but is slower due to the java startup time.

Alternatively you can use a dbus library for a programming library of your choice, to communicate with the signal-cli daemon.
Also see https://github.com/AsamK/signal-cli/wiki/DBus-service#user-content-send-using-dbus-send

**Comment by Tsjippy** [comment]
Ah I assumed there was no startup time with the —dbus option. Makes sense now
