### ISSUE TITLE
Getting RATE_LIMIT_FAILURE in message response

### ISSUE THREAD

**Issue by nkray2704** [AsamK/signal-cli#1161]
Hi Team,

When i am sending a messing in group or individually then for some number, i am getting below response.

[
  {
    "recipientAddress": {
      "uuid": "c118bd9d-cf95-4bce-939f-2deb9ef44a65",
      "number": "+918587899197"
    },
    "type": "RATE_LIMIT_FAILURE",
    "token": "a36f8c39-5c1b-4f7d-b5c0-572fbe928efa",
    "retryAfterSeconds": 86400
  },
  {
    "recipientAddress": {
      "uuid": "8f2c52bf-9522-4bc6-a40c-da48bccb1110",
      "number": "+918858142021"
    },
    "type": "SUCCESS"
  },
  {
    "recipientAddress": {
      "uuid": "8fd77d30-b77e-478c-ab06-18b9d9605686",
      "number": "+919667579218"
    },
    "type": "SUCCESS"
  }
]

Please help me to understand the situation. In which condition we will get response. Please help me to resolve the issue.

Thanks !!

**Comment by rajat2015** [comment]
Please help us in understand when we can get RATE_LIMIT_FAILURE in response and how we can avoid it. We are getting RATE_LIMIT_FAILURE in almost every alternate message. We have added anew number in  group but on new phone number also we are getting this in response. We are stuck in our task due to this RATE_LIMIT_FAILURE response. Solution will be mush appreciated .

**Comment by AsamK** [comment]
When you get a RATE_LIMIT_FAILURE, you can lift the limit by solving a CAPTCHA, see: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#submitratelimitchallenge
