### ISSUE TITLE
Debian GNU/Linux packaging

### ISSUE THREAD

**Issue by ghost** [AsamK/signal-cli#117]
Bonjour,

For information the Debian GNU/Linux package for signal-cli is being worked on. For more information about progress see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855457 . If anyone is interested in participating or has specific requests regarding packaging, speak up :-)

Cheers

**Comment by dachary** [comment]
@AsamK would you be so kind as to explain the rationale for depending on a fork of libsignal-service-java (https://github.com/Turasa/libsignal-service-java) instead of the  upstream ? I will have to explain that when packging this fork instead of the corresponding upstream.

Thanks in advance :-)

**Comment by AsamK** [comment]
Hi dachary,
Thanks for taking on the packaging.
signal-cli originally used a forked libsignal-service-java library to work with websockets instead of GCM, the original lib was missing a piece for that. Later the fork was extended to support provisioning as the slave device, i.e. connecting signal-cli to an already existing master device. The original lib only supports provisionig as master, probably because the Android app doesn't support provisioning as slave either.

So signal-cli is using the forked libsignal-service-java to be able to link it to an already existing signal account from signal-cli or Signal-Android.

**Comment by dachary** [comment]
@AsamK thanks for the clear explanation. I'll proceed to package https://github.com/Turasa/libsignal-service-java first and keep you updated.

**Comment by dachary** [comment]
Unfortunately there are two blockers to get signal-cli in Debian GNU/Linux, as explained in [the corresponding intent to package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855457#11). For these reasons I won't be able to package signal-cli.

@AsamK I thank you for your support and positive feedback and hope these blockers will be resolved in the near future.
