### ISSUE TITLE
ARM64 native binary compliation conundrum

### ISSUE THREAD

**Issue by julianfairfax** [AsamK/signal-cli#1222]
I'm trying to compile the native binary for ARM64, by using a PinePhone. I followed the instructions from https://github.com/AsamK/signal-cli/blob/master/README.md#user-content-building-a-native-binary-with-graalvm-experimental, and ran the following commands:
```
version="$(wget https://api.github.com/repos/graalvm/graalvm-ce-builds/releases/latest -O - -q | grep tag_name | sed 's/.*m-//' | sed 's/".*//')"

wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$version/graalvm-ce-java19-linux-aarch64-$version.tar.gz
tar -xzf graalvm-ce-java19-linux-aarch64-$version.tar.gz
PATH=$HOME/graalvm-ce-java19-$version/bin:$PATH JAVA_HOME=$HOME/graalvm-ce-java19-$version gu install native-image
sudo apt install build-essential libz-dev zlib1g-dev

git clone https://github.com/AsamK/signal-cli.git
cd signal-cli
PATH=$HOME/graalvm-ce-java19-$version/bin:$PATH JAVA_HOME=$HOME/graalvm-ce-java19-$version GRAALVM_HOME=$HOME/graalvm-ce-java19-$version ./gradlew nativeCompile
```

The problem is, compilation never completes. I think the longest I was able to get it to run for was 45 minutes, at which point it was still not done compiling, still at 90%, which it stays at forever after passing the 5-10 minute mark. Usually however, it doesn't even get to 45 minutes, freezing before then.

No matter how many times I've tried it, I have never been able to get signal-cli to compile with the native binary. And, the standard binary suffers from the performance issues described in https://github.com/AsamK/signal-cli/wiki/FAQ#performance, especially on low-powered devices like the PinePhone.

Any solution to this would be welcome.

**Comment by bublath** [comment]
I tried to compile the native version on my Raspi400 with 64bit Bulls Eye and the Java17 version of graalvm.
The first attempt failed as apparently the 4GB memory where insufficient (I watched memory and swap maxing out with htop before the machine became unresponsive)
In the last retry I reduced the workers of gradlew using
./gradlew --max-workers=1 nativeCompile
and this one succeeded.
If anyone is interested the (zipped) binary of signal-cli 0.11.8 (well latest master per today) is available at http://bublath.de/signal-cli.zip
The unzipped file has 110MB.
I have not run other tests than printing the version so far, but it seemed to execute ok.

**Comment by m-ueberall** [comment]
> I'm trying to compile the native binary for ARM64, by using a PinePhone. I followed the instructions from [`master`/README.md#user-content-building-a-native-binary-with-graalvm-experimental](https://github.com/AsamK/signal-cli/blob/master/README.md?rgh-link-date=2023-04-08T14%3A03%3A26Z#user-content-building-a-native-binary-with-graalvm-experimental), and ran the following commands: […]
> No matter how many times I've tried it, I have never been able to get signal-cli to compile with the native binary. […] Any solution to this would be welcome.

@julianfairfax : Seeing the answer by @bublath earlier today, I retraced your steps in an Ubuntu 20.04 LXD build container (using 'GraalVM 22.3.1 Java 19 CE', '19.0.2+7-jvmci-22.3-b12', gcc (linux, aarch64, 9.4.0)) on an [OCI Ampere A1 Compute instance](https://docs.oracle.com/en-us/iaas/Content/Compute/References/arm.htm#ariaid-title3) (4 OCPUs, 24GB of RAM). Compilation took 3.5 minutes (on tmpfs `/tmp`) and required approximately 9.35GB of RAM (according to `htop`) before it produced the below:
```
-rwxr-xr-x 1 root root 110576400 Apr 16 18:27 /tmp/signal-cli/build/native/nativeCompile/signal-cli*
-rw-r--r-- 1 root root        25 Apr 16 18:27 /tmp/signal-cli/build/native/nativeCompile/signal-cli.build_artifacts.txt
```

I then moved these files out of the way and reran the previous command with `--max-workers=1` as suggested by @bublath, but the results (duration, allocation of RAM) stayed _exactly the same._ (Not sure whether other options are required in the above environment—I did not browse through the documentation yet, just wanted to run a quick test.)

So unless the (successful) reduction of the number of workers also affects the required amount of RAM, the only option would be to use a more powerful build machine. If you're lucky and the free offer linked above is still available, this might be your best bet (…until someone forks the project and attaches an ARM64-based GitHub runner to automatically produce binaries for each upstream release or the like).

**Comment by bublath** [comment]
Thanks Markus for trying. That confirms my suspicion that actually every retry (needed 3) brought me closer to the target and it was just a coincidence that using the max-workers=1 in the last attempt seemed to help, as the native build in gradle seemed to use only one worker anyways. 
I however see that Java (or graalvm in this case) is forking of a lot of processes. Maybe there is a way to restrict the parallelizm of Java or the amount of RAM used.
It could also help to significantly increase the amount of swap space - compilation would probably take extremely long, but at least it might run to the end (I only had 100M of swap configured).
As my binary was created for Raspberry Pi, I'm not sure if it will be useful for PinePhone which seems to be the target device for @julianfairfax

**Comment by m-ueberall** [comment]
> As my binary was created for Raspberry Pi, I'm not sure if it will be useful for PinePhone which seems to be the target device for @julianfairfax

IMHO, as long as you see the below, it [_should_](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#index-march) be compatible (given that the [PinePhone](https://en.wikipedia.org/wiki/PinePhone) uses an [Allwinner A64 ARM Quad core Cortex-A53](https://en.wikipedia.org/wiki/Allwinner_Technology#A-Series_2)), though it _might_ require an additional `-mtune`:
```
root@ubuntu2004-build-arm64:/tmp/signal-cli# gcc -Q --help=target | grep march
  -march=                               armv8-a
```

Another question would be whether it's required to produce a _statically_ linked binary (depending on the Linux distribution in use which @julianfairfax didn't mention), because the dynamically linked one (here: built on Ubuntu 20.04/Focal) requires the following:
```
root@ubuntu2004-build-arm64:/tmp/signal-cli# ldd /backup/webdav/ionos/pbuilder/tmp/signal-cli
        linux-vdso.so.1 (0x0000ffff8f496000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000ffff88ad2000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff88aa1000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff88a8d000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8891a000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff8f466000)
```

**Comment by bublath** [comment]
I wonder why I did not see this. Probably even the native build process includes the libsignal-client jar file that is provided in the standard package which is for am64. I'm not sure how to replace this in the build process, but maybe you can place the library somewhere in your LD_LIBRARY_PATH (e.g. /usr/lib) - I have a matching one here:
https://github.com/bublath/FHEM-Signalbot/tree/main/aarch64-glibc2.31-0.22.0

**Comment by bublath** [comment]
You're right. As soon as I try more than printing the version, I'm getting the same issue and can't make it use the correct native library.
@AsamK Can you help to understand, how I can include a different libsignal_jni.so right away in the build process? I guess the amd64 one is fetched from some repository and then I see no way to replace it when compiling on aarch64

**Comment by bublath** [comment]
Exactly - that is how I created the library quoted above. The problem is that with the executable, I can't replace the shared library and also cannot set something like
 -Djava.library.path=...
when starting signal-cli.
For building the executable, I would need a way to tell gradle to use my own version of libsignal-client-0.22.0.jar that includes the aarch64 libsignal_jni.so instead of the standard amd64 one. But since I really don't know how all the build tools work, I have no clue how to do that.

**Comment by AsamK** [comment]
libsignal-client is a transitive dependency of signal-cli, but you can exclude it and add your libsignal-client-0.22.0.jar file, by adding the following to the main build.gradle.kts file:
```kts
dependencies {
    implementation(files("/path/to/libsignal-client.jar"))
}

configurations.all {
    exclude(group = "org.signal", module = "libsignal-client")
}
```

**Comment by bublath** [comment]
Cool that this helped. Since the RAM requirements for the build are exceeding that of a Pi3 or your other device by far, i don't think there is an alternative to cross compiling this on a stronger machine. There are probably ways to properly configure the build scripts to create aarch64 even on a PC (or GitHub servers), but I'm no expert in that.

**Comment by m-ueberall** [comment]
@julianfairfax : You can, e.g., use [pbuilder](https://pbuilder-docs.readthedocs.io/en/latest/usage.html) in conjunction with[ QEMU](https://www.qemu.org/) and _binfmt magic_ to create a chrooted build environment for a number of architectures nowadays. I currently use this to experiment with a `riscv64` toolchain while waiting for suitable hardware for the home-office. (Whether GraalVM will work in such an environment would need to be tested, though.)
[@AsamK Maybe it makes sense to convert this issue into a discussion or open a related one which refers to here?]

Seeing that the native `signal-cli` binaries save quite a bit of RAM, I decided to slowly deploy them on all of my amd64/​arm64 hosts. Since I therefore need to build them on a regular basis whenever a new version is released upstream _anyway_, I can as well make them publicly available. For the time being (i.e., until a public GitHub/Codeberg/… mirror becomes available), the arm64 binaries can be found at https://media.projektzentrisch.de/temp/signal-cli/. Maybe they work for you as well until you're able to build your own?
(Interestingly, my binary is smaller compared to the one by @bublath which must be related to the `libsignal` library?)

**Comment by bublath** [comment]
@m-ueberall: I just did a "strip" command on libsignal_jni.so and it went from 19MB to 2.7MB. I never thought about checking for symbols before. Could explain the difference.

**Comment by m-ueberall** [comment]
> @m-ueberall I'm using your binary to build an arm64 Debian package for signal-cli: [gitlab.com/julianfairfax/package-repo/-/blob/main/signal-cli/build_deb.sh](https://gitlab.com/julianfairfax/package-repo/-/blob/main/signal-cli/build_deb.sh). Please let me know if this is an issue for you, and I'll remove it.

Not at all! :smile:
