### ISSUE TITLE
I'm having alot of trouble getting tokens for the captcha

### ISSUE THREAD

**Issue by Zombie-Ryushu** [AsamK/signal-cli#1253]
I'm having alot of trouble getting tokens for the captcha Every attempt I make results in:
Invalid captcha given.
or
Failed to register: [429] Rate limit exceeded: 429

**Comment by turingmachine81** [comment]
I was getting this recently as well when following the instructions on https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha and running the command:

`signal-cli -u [UK mobile number] register --captcha signalcaptcha://signal-hcaptcha...`

However strangely it's now returning a different error:

`Failed to register: StatusCode: 502 (ExternalServiceFailureException)`

In case it makes a difference, I don't have a smartphone (just an old 2G Nokia), so I just use `signal-cli` as a way of being able to use Signal Desktop (which is working fine by the way, it's just this registration step that seems to be failing).

**Comment by lampnout** [comment]
Hey @Zombie-Ryushu,

If you are trying to link additional devices, take a look at https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning).

I'm not sure this is what you are trying to do. Hope it helps.

Regards

**Comment by kmille** [comment]
same here. I tried it multiple times. You have a single try thent you are rate limited for some time.
I always get "Invalid captcha given."

```bash
signal-cli@ef860597331e:/$ signal-cli -u +4912312312 register --voice
Captcha required for verification, use --captcha CAPTCHA
To get the token, go to https://signalcaptchas.org/registration/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
Everything after signalcaptcha:// is the captcha token.
```

```bash
signal-cli@ef860597331e:/$ signal-cli -u +4912312312 register --voice --captcha "signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.challenge.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQnBS1SRWYR_CgzyeMitgm3f
uypOAEWovW2t0OF_8ieK85i8eZav-vX5QeefRnZ1VLMbdbpKqkqH17d4ppLrwUKwz44u6yfMmAo2TP7dv9N1A6BiZnhO5v7O5ZwkeVo644_CG5NMDAsXPgIWJhtXWjD5pQPzDKHWHkTIEeoTb5xNPO9HkHXHVK5g2D3m1QD13bcIEskaiMWSq-M4_2mPia5uqfaW5surE4U3w5-p4EWoCe1LcN8o36VM3gMVPdPJMuzk7lN
rwObxITssXN1fmkJg6i5IkTaoPTg60mZyxOegaS81S55QARd-TaDRvk2BHXZaK0s16fBap_bHGwJ7juwVLinLxRcAT9pHqjPaOhwKlgsXgU4Yq6ThAWwJEQhti9m81XT2HeHhOEKYYW9f7VSdUQrOysTVdS0N5AyL2ervb9JssFsZzcskTg9L12I6Ls3GehTMIhYy7ph8JX5-3jH5F3GPA8ZAc2_0UOHBXlW31nMJbSN8-w
A9q1fIh2f09QNwxdiqekyTNob5Bc6bZ8IojViSweDUlJvkCz2jvX2koyYyvKTPwyvl-3sWxkMv6XYXbv199lMroiJdhRpi984qQUvQIppjP2EZC1icJo_34M9pVGG7R3BMBOLgGpG9i9hcqlGYzPrSdUFSCor3f_Vz7BVfSiZTz_siMH0njNvYVIfYlkgHIvVSHQS91DgiYlnEh2xG5Reqgblm7UKWnDjkf8za5RaJv68Nn
WgvhTSW5rIL6HVHnFBQDXWbJKN9ksEPM2QdSUj-HqzIXS-OG0Y9GZcCeLgY-hxFMhJjWcC8gWaYTgi0hyP22R9ZCzdv_EMwA4EXwlrxcEXeF_doH0SsaWAkHLmncl4F-gy53k-yv5PxfPqcE4rzFZY_wycbXP14tQBx25m3wnzVpF-rE6JItN37pywGkcsJfoTxpYzxK3XQhW-YxV4XsvZk32qSCgjRwuxVR6IyUNEQv_F9
IUeSohFvpmIv2zeqnrDTyr6AbbcN81UzCA3S3F30bolE7jaxX2kwz-oTJepmPQTgwyEKs_F6beGih5RBph88kKr-fWbWCQhBXtz2g6T615aIxi_S72g_smu5nytt8qsbRrezb6egfxoO4q8FTXCRaMQcjVuawhWHIP11Tn-8pBwl1tgqbF7wVmi_v2-10SbRwYNzVO18YtIwA5ncchS3cikJDWbejGxR39ny9iN1IWn9uXP
NSibXcSgy3hofxSb_GIkVWFtAPTOTCGnVIxrCad9gIeMH02mHuLaOGRVJ8HwFiQlDiMGt-qRIYm4EGhnOKXjsYz7TA2W6sIlSlW8IkPYymb2J52r_CGRCETKfexP_cgyw1C8TFgmZMpTdSAKsHYdasgJ6peUW9dARiKLcpNICFBnRw0N62a5nwniYLYmoCZl7jFs1blglJjDD_Y9ir9TAJMlBLgqNxow4Y13wfBm9z3FV4N
lwgo4PB1Zx40JAsk7kQRJnQE35ZcmQ_xCbeDNLKFvWBVU8z3bV6sdL9aF_JiSVT5RJEJibCF-Q6zGSBwXSQO4NFpgZrLnvUA02pwNO7C3n8F9JbqRsLCqOfXXJgePi4uj3QnjiGGWf6oF2G_jzYV330b38NhirevIwJlG-A2qmZ8oQb6AxsY32wbtxu-gOOmeHME8XJM-b9bxgOvITxqHFyAbJBLSLmS9iuAiRKj6hLf4pb
W-nTWVlvzJ6Bx8uk5iea5uYXq2AR-GmnxrRajNKEIHNASirJTg9BG419k-ZyclA_K24qzrsjYAyaFeiFZfpVALRsFqwYXaZh-Onr_PnYQd8TDR9Q1poR_TuqfMZIwJbx_OBuMAKfreabOopQ-PXBMz6INyDSFXgj-iA0fOHwEPVGiGt3kyr5xHG6pdXIgHE-7Mn--r4co-oRiuBk_8-JAoGTnBni7SSW_8YIA_Ya3m0By3b
onk-91_cMNBDZ0cwlP1rWG7YaPsV48M6ZQnui7sXUUt1KK2BDu27se6uw_tX4CVRTE7Mx3bbbV-2aqCJ6-PXys5EIAgIBfV5ZmEaWRZRiTIUdvtw9yukF3PKh8QsueWoi7EMXyNWhSF-k0tQP_xCLQdLKbCp0vHUwRWhDenifi4N8BKOxDoVuBfRpHOJrv2XtKZeYiHD3YOtOoTMMireXGuPkLjULm-GfJv-WCnO6YAS9U3
esrzfpQQbtbB5E0tfcl-iMsAR4WavnqLn9B4F91B8Y02ad4Vfao-t1PoP9iVOEtOcqd_a3WPSbGY0pVNKbU2tnGXa78O7m1Wx4dJS8O2_PBKHb4HiLpcXCLsBJyZuGjnbnWRRBDHm6AclvOYonJJ041o2KnNW9xuHZzlYOTjq5cp-oZ3CxLy4iUTSMlHB3UYFfP9UsVIc0DWbhpIOkJCQLmuWpJjNXpwnBeMfxmoqxPheRH
rxf5plJMw1y9XBa6xAvnyU6CZhetfMgMmGX_EdbJpwETlNbCwbArOMG25S1JwX820gouPHuG_6-2ArK2_95vHBP6hAlYoDXshF48F911q8QZEUQyTIWhPrdkLlyIXPKojVOggPTuRnLFEwbNk6QkMtGhslMGWO8Q6mVdQfT-GWU8I34RftdG4irsltYKP2FKTTLIaXyFS_-CheqexoePVC2OHKo8VPWuo9Ja8_T5hx7HDIL
FeTTMhCc534arMThDLCYbMaTxVQr2OZ-An55aDHeD6xRAypgckhmUVBB7uk7nQj5mrnpz5nuada7DPJ1yIUtEj-kUN865RVmV3owEcIQJTF0fWpB0dNLn9fZ7w8ri3LDHzrDkW_CDyD7LOFsRM2w6bqjr1odSnZLOVj9jcDMwveNBp2AjObdqHYKALv2hxcUi8HPW7koJWqnCv29_yqD0t8PDVzsr-eX52Ubu-HPWD0NPSX
Rv-q4FEezx328eCOPTiMq7fADnd4BI67alSoeYBnPrjQ2r-tJQYZHvKAcZNbNzSBZt-XCF3qBKdm_I-voclMLRueS9SCoF_TIj2hbWFytqPqgpZzYQ3VQZybF2ctzGtLdjZPEAFohoykJqP9A0gKQqVJB6Fdf2XCs7le8KbaUrHBgVogka220KcHvr2NOAbKzp4EHwj4HIicBWcBIOAS-j4euGj7v_-ymWbkKClRJ12akqe
0zl7qsJRNDceR0eKVaLoEXqGF_L6bBb6HrZFI9kewA-1d62ayZlr3_oqk0_sPmG2prbQMU2rr-qyC2ytxFTioZMXclAKQMRPa751SmE3HYEAx-a32yickGjORn2SOJhqFL5iNnhR05vls0UzRhSoOO8OjTo0a7yI9yObDhDh_n-qetoxs9gk3-Uxw_IPb1QA7mXu0XvwCw6NleHDOZIjTbKhzaGFyZF9pZM4DMYNvonBkAA
.FIoD1sBFS6tO05ZZVC_ejyTiyfp2cUdlrUkvKB_7mOU"
Invalid captcha given.
```
I  tried both links in https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha, but still no success/registration -:-
Any hints?

**Comment by galgazur** [comment]
This seems to be an error in the documentation here: https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha
This:
```shell
signal-cli -u $PHONE_NR register --captcha signalcaptcha://signal-recaptcha-v2.someshortercode.registration.someverylongcode
``` 

Should be this:
```shell
signal-cli -u $PHONE_NR register --captcha signal-recaptcha-v2.someshortercode.registration.someverylongcode
``` 

I.e don't include `signalcaptcha://` in your captcha code

**Comment by xyz-nobody** [comment]
I always put the captcha between '' with signalcaptcha://.

I've just changed my line and I've just tried to register again, with signalcaptcha:// or without I have the same problem, it says invalid captcha.

I have the impression that it's since they switched to hcaptcha that we've had a problem.

signal-cli -u +491551XXXXXX register --captcha 'signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.challenge.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQn-Ay831RawVFnRyHrhusXnNVU82D6DoYiFsbA9a7oHNrANx-K5kC0xmdL1CRnrB8isEJd605ceBmjIgt4wf4sCQWyVpoPm5D3xIrvKrRYkrbr1Cav1bFUkj6WbBqyU28q3163r2RJmtA0dMBa8llWdtJkkKxh-85vv-PmMScQSUH7COpRbM0w6oxLjXmUiRSHWSaR__JybCuYt3sYzlE4tLnSu1UUFjSv9uHcFlR5VTyO0ejuPPDA-PEZtR93tvDeInHpu0YrJ74YXGGVf7Be6higbJ0cuU3Mg-bdpla2JQBkbU9uC0aBY6sSw2sijHrAbArF2EdNqJa7c6Lq5ICSSJrO9AXYZBbT31gF0Bg09p2TK9SA9z2mCox48YMowjUU22kgQDVGFyNxEF9aWSPttjY24vb8IzHIL-6kNo3aYDolWypiu-34gQjcvFrVM3EyaylYVm-hc0goPeXoKxkz7AJ6l0nXWpSkGVLneDrvGqghDClFBrEn5BxuoIVOO564Bo1QeI1ZUNGgEq5SWUyLaiDy_oPrOSKtwWOYkFjVsu1o_eW3OxuYdXHpObiypyA5YxBVyB4G8LUfLqXQza_UtniHB8QPGcS7qVH6VTRhQ5EzO4mjZ_7rAuMwyWXSMNU3akONa9ErCKw7ucShr9uxwlkuzyiqsdtH-fAE5REDPL9-q48wFovifVGSTQJzGzdREU_jIpMzKLitcq-PsvgCiz24mJh3Oz2pHtpOSgBEYp9HBuKrGkNpRBNGaKYbS26JrHcQYoNRsevNwDSxvxVhsOKZzVjnobEoQZgCoc2L40XT0-ECJ-Op87xV-fPd4MAjpkU0WbIVmJb30d2zsvOPaZOT0be8B6wgZWyJ-R0UWkRbZaFlRE-Gu3TIM8pOyPmvVLdtYA46W_h0smaNmUOX8qq3apXwl8-t_4U-jHwU0JahC4g7dL33PdZFhB5HhvcABxsIzDW6eFogdEKW5HyMfT5meM1_pJ5Y66JrYOE_vhfBzD-AaG9RBojs9i5Pi-OjaDbvTBZKlbTH5CB96rx-NzKnJlYZGRyKHiRfuB7eM86jhaoVLNuGa4Vjp97PTt4XxTb7B__g9ZcKlr3RQBmw2dZo0TIiJoJ8lIkZT_lOnseDKYf9hHla92rjzfyJ_2Og5mZanreBVRENJVGi7tT85aCHSCDINJRRWjdUCoaoxz-URIpgQpkAauLn6elBx0NqIENjjUPXR4jn1ZqMOKAIKrCCzQMhiIj6_II5cV6Lnk0aNkDSgBSQMVMhvBK0w3MgS-exmcc2aD2sPmEonHZ2XnjIxjsZdUrWXwxgIQXD6O7iVKIJVHChTqNwDoUoX3FGQcwuQZZdf3LNFwI1-99w04o__wZxZh5PQHhDfNgEVISAYuPP01Cl-GgpNUPWuYLeHnfySPo_kVFA4InfQk5KMrH3AdEnfXnvNPmLZP_fW6cM1xlvWr1-Baxwv9uaZuNNa0RM8SvLrHLAhP_FE93zr1-xbN7499jnoM0mDUWLSz4b-bC05rtVOlH-WSHGBYmsnRDGhGqqRB_Y66T7kOU_x1mJYhbo6cACXHTomQOO_jmeKOQL6L29VyhxS6vqDmNmtg2yVxzHMDJ07LrNkJumfoxly7fm4b7136kCd2W06JuEtDpFiZ_YA88Fqv2hTJeaZcQi3R9vWQ6xQTaL-mvE5Xb197AI0GXd6wuL0qqr5YcBzf_53m8VXgDqreKRUBrdAzGMDLrZ_Letcsr8XzeJQjP_4Y71Qtf85hI2A8U3yMVF-Ki9aOtknPeQkVG1a-gJJoepvWXareoGM9dng2KzzuTq0io_EFz84S0fk030_W3lp93cTIw8h3BPuiQ2kb4VY65rGkJYMTG8ipKNOvYf3H7nm7otHh4YzvhAasndFnXCRAyY-8t4sYNRli2hhKHzMKi-y0wJzdHlgXoFJE54G9FwIXWA45GFzn8cn3dqWX-fPk9lmh65EgJmPTiG6N0SorfzbsiCKbTL7WIC7PMjIE5WtYmJ46yWVOQeSwnZTMUYeS6tcfqbVuy49PUnT0KkKYSBM1yc1I155jTiyu8JgBg3U-QKgtQL1Wtw6Km4uyDCdR6S57MQps7tRMFfSKzAiEUVdI_bNgYJRwoNi3uUKfO6heQYMYDd_-fvhEF3vGCrWC12RjypuBuXqAlMZRJGkmvcFSmyRiA4f4dOi854KUFyxNWtDwuhLop9LgkjC1YoO35QKeCWTt9dM-rGD9EuzQtu0O-0QpXjFXK-oSSDwgj0_50bPWMuOIaySmYodIut3xCBEaXknWMzoTKMnl8GV3j0lHrAC6FoMblNHjILWtc2w3VKUEuHAmyJnuq2trMZatocLxyKsUBoxuhRHf4rjczFaR6IDh3WrmZC1s4ULeRKihRMKBj4F5WdQjyFGlplUxErrgQ2VRujtEyYda-2zVYnVCsdk2TdnqMoFIguzRZxbaPUatnjMAufgbmYPBcMxhxsfMVH--x869j_QRrDtIXwUoNYC2B78ezxNCPwhYMBYJrK6AetaCYZPSbSksVRmtmdH8R-OCuytA1TE4WzHyTkmmLK3AUjzCt6yO9fYrjJyjmzsSJi2ONeJ-yrU-OFvmgPheJQs-SLcowI6j-9ZrWMzct6vorKSzBTUp1iNfmdFbYg9e0xWU9pklgZspP54sY9oW078EzTMP-k37rhqU41-Yxh2cPrFaTVpN-OltybglW7OXcCvaB8G7fOdN1nwYO8t8Nva5I-COSCujlmqkJ8FlBOlDBvGibycuOnx3pNar9aVwg9CnrznfRDA0TBJjrwGoNHbtTmw-K6P5hW6_JIOfUT4eVbIYFEwBHy6GF9BqTj2xcQOLU6TJKD5ve9s0OQPLxudDxGZRGH4NtnZ8uC7udnCVV3Pz9-aIo5q5cyfZaNTzJpuirsrTe8dYn_50NvKBV_zIXvnEqixZT6g7ogtri2C_zRyb_QVuA1a7Z0S42oJu3t5XOk0i6siaJAXsFnRTqWWjiHz0YRUX5epwkFnUM8FQQ3M9xovUZXbmdXNDQnWOm54ujIvNauRHKJr1EVIsD5PvoBzdoYH9D0iu82o0SothdSsBh3czsRkza-4oFM14w_OTV6fggHOrbCCbHw8rXWVUgZV-d9rEkmeXYSEbMKsaFyEJBmXwyEkZQqn0xeHRC35UzSWBJeY5m46G23N-2AcjzynkuOKchemS7r8swOYkM5Wuz3g44_6nvR4ow1PWOQR2HYLOsAgRG5nsbaS_wvBzQxHIWsj8jADcTiJ9DtMsXQ8t9ISlgJc4YDmY3wqCNTQinD-ESJaypUM49kb3dPOl8_MsfpJ5UTEtahuq6lUXlPYdyjtNXi59pSmIm8diaclbT1Q3ztEG7BnixUuiRxwwgn1sgScJyBJVP8RzNHhVNTztwBd4ECjZXhwzmS8Imuoc2hhcmRfaWTOAzGDb6JwZAA.w3ekVqkTUI0oBQZphWHsaD0DDVE9i0X37uTXqGdncsA'

Invalid captcha given.

or 

signal-cli -u +491551XXXXXX register --captcha 'signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.challenge.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQn-Ay831RawVFnRyHrhusXnNVU82D6DoYiFsbA9a7oHNrANx-K5kC0xmdL1CRnrB8isEJd605ceBmjIgt4wf4sCQWyVpoPm5D3xIrvKrRYkrbr1Cav1bFUkj6WbBqyU28q3163r2RJmtA0dMBa8llWdtJkkKxh-85vv-PmMScQSUH7COpRbM0w6oxLjXmUiRSHWSaR__JybCuYt3sYzlE4tLnSu1UUFjSv9uHcFlR5VTyO0ejuPPDA-PEZtR93tvDeInHpu0YrJ74YXGGVf7Be6higbJ0cuU3Mg-bdpla2JQBkbU9uC0aBY6sSw2sijHrAbArF2EdNqJa7c6Lq5ICSSJrO9AXYZBbT31gF0Bg09p2TK9SA9z2mCox48YMowjUU22kgQDVGFyNxEF9aWSPttjY24vb8IzHIL-6kNo3aYDolWypiu-34gQjcvFrVM3EyaylYVm-hc0goPeXoKxkz7AJ6l0nXWpSkGVLneDrvGqghDClFBrEn5BxuoIVOO564Bo1QeI1ZUNGgEq5SWUyLaiDy_oPrOSKtwWOYkFjVsu1o_eW3OxuYdXHpObiypyA5YxBVyB4G8LUfLqXQza_UtniHB8QPGcS7qVH6VTRhQ5EzO4mjZ_7rAuMwyWXSMNU3akONa9ErCKw7ucShr9uxwlkuzyiqsdtH-fAE5REDPL9-q48wFovifVGSTQJzGzdREU_jIpMzKLitcq-PsvgCiz24mJh3Oz2pHtpOSgBEYp9HBuKrGkNpRBNGaKYbS26JrHcQYoNRsevNwDSxvxVhsOKZzVjnobEoQZgCoc2L40XT0-ECJ-Op87xV-fPd4MAjpkU0WbIVmJb30d2zsvOPaZOT0be8B6wgZWyJ-R0UWkRbZaFlRE-Gu3TIM8pOyPmvVLdtYA46W_h0smaNmUOX8qq3apXwl8-t_4U-jHwU0JahC4g7dL33PdZFhB5HhvcABxsIzDW6eFogdEKW5HyMfT5meM1_pJ5Y66JrYOE_vhfBzD-AaG9RBojs9i5Pi-OjaDbvTBZKlbTH5CB96rx-NzKnJlYZGRyKHiRfuB7eM86jhaoVLNuGa4Vjp97PTt4XxTb7B__g9ZcKlr3RQBmw2dZo0TIiJoJ8lIkZT_lOnseDKYf9hHla92rjzfyJ_2Og5mZanreBVRENJVGi7tT85aCHSCDINJRRWjdUCoaoxz-URIpgQpkAauLn6elBx0NqIENjjUPXR4jn1ZqMOKAIKrCCzQMhiIj6_II5cV6Lnk0aNkDSgBSQMVMhvBK0w3MgS-exmcc2aD2sPmEonHZ2XnjIxjsZdUrWXwxgIQXD6O7iVKIJVHChTqNwDoUoX3FGQcwuQZZdf3LNFwI1-99w04o__wZxZh5PQHhDfNgEVISAYuPP01Cl-GgpNUPWuYLeHnfySPo_kVFA4InfQk5KMrH3AdEnfXnvNPmLZP_fW6cM1xlvWr1-Baxwv9uaZuNNa0RM8SvLrHLAhP_FE93zr1-xbN7499jnoM0mDUWLSz4b-bC05rtVOlH-WSHGBYmsnRDGhGqqRB_Y66T7kOU_x1mJYhbo6cACXHTomQOO_jmeKOQL6L29VyhxS6vqDmNmtg2yVxzHMDJ07LrNkJumfoxly7fm4b7136kCd2W06JuEtDpFiZ_YA88Fqv2hTJeaZcQi3R9vWQ6xQTaL-mvE5Xb197AI0GXd6wuL0qqr5YcBzf_53m8VXgDqreKRUBrdAzGMDLrZ_Letcsr8XzeJQjP_4Y71Qtf85hI2A8U3yMVF-Ki9aOtknPeQkVG1a-gJJoepvWXareoGM9dng2KzzuTq0io_EFz84S0fk030_W3lp93cTIw8h3BPuiQ2kb4VY65rGkJYMTG8ipKNOvYf3H7nm7otHh4YzvhAasndFnXCRAyY-8t4sYNRli2hhKHzMKi-y0wJzdHlgXoFJE54G9FwIXWA45GFzn8cn3dqWX-fPk9lmh65EgJmPTiG6N0SorfzbsiCKbTL7WIC7PMjIE5WtYmJ46yWVOQeSwnZTMUYeS6tcfqbVuy49PUnT0KkKYSBM1yc1I155jTiyu8JgBg3U-QKgtQL1Wtw6Km4uyDCdR6S57MQps7tRMFfSKzAiEUVdI_bNgYJRwoNi3uUKfO6heQYMYDd_-fvhEF3vGCrWC12RjypuBuXqAlMZRJGkmvcFSmyRiA4f4dOi854KUFyxNWtDwuhLop9LgkjC1YoO35QKeCWTt9dM-rGD9EuzQtu0O-0QpXjFXK-oSSDwgj0_50bPWMuOIaySmYodIut3xCBEaXknWMzoTKMnl8GV3j0lHrAC6FoMblNHjILWtc2w3VKUEuHAmyJnuq2trMZatocLxyKsUBoxuhRHf4rjczFaR6IDh3WrmZC1s4ULeRKihRMKBj4F5WdQjyFGlplUxErrgQ2VRujtEyYda-2zVYnVCsdk2TdnqMoFIguzRZxbaPUatnjMAufgbmYPBcMxhxsfMVH--x869j_QRrDtIXwUoNYC2B78ezxNCPwhYMBYJrK6AetaCYZPSbSksVRmtmdH8R-OCuytA1TE4WzHyTkmmLK3AUjzCt6yO9fYrjJyjmzsSJi2ONeJ-yrU-OFvmgPheJQs-SLcowI6j-9ZrWMzct6vorKSzBTUp1iNfmdFbYg9e0xWU9pklgZspP54sY9oW078EzTMP-k37rhqU41-Yxh2cPrFaTVpN-OltybglW7OXcCvaB8G7fOdN1nwYO8t8Nva5I-COSCujlmqkJ8FlBOlDBvGibycuOnx3pNar9aVwg9CnrznfRDA0TBJjrwGoNHbtTmw-K6P5hW6_JIOfUT4eVbIYFEwBHy6GF9BqTj2xcQOLU6TJKD5ve9s0OQPLxudDxGZRGH4NtnZ8uC7udnCVV3Pz9-aIo5q5cyfZaNTzJpuirsrTe8dYn_50NvKBV_zIXvnEqixZT6g7ogtri2C_zRyb_QVuA1a7Z0S42oJu3t5XOk0i6siaJAXsFnRTqWWjiHz0YRUX5epwkFnUM8FQQ3M9xovUZXbmdXNDQnWOm54ujIvNauRHKJr1EVIsD5PvoBzdoYH9D0iu82o0SothdSsBh3czsRkza-4oFM14w_OTV6fggHOrbCCbHw8rXWVUgZV-d9rEkmeXYSEbMKsaFyEJBmXwyEkZQqn0xeHRC35UzSWBJeY5m46G23N-2AcjzynkuOKchemS7r8swOYkM5Wuz3g44_6nvR4ow1PWOQR2HYLOsAgRG5nsbaS_wvBzQxHIWsj8jADcTiJ9DtMsXQ8t9ISlgJc4YDmY3wqCNTQinD-ESJaypUM49kb3dPOl8_MsfpJ5UTEtahuq6lUXlPYdyjtNXi59pSmIm8diaclbT1Q3ztEG7BnixUuiRxwwgn1sgScJyBJVP8RzNHhVNTztwBd4ECjZXhwzmS8Imuoc2hhcmRfaWTOAzGDb6JwZAA.w3ekVqkTUI0oBQZphWHsaD0DDVE9i0X37uTXqGdncsA'

Invalid captcha given.

or 

signal-cli -u +491551XXXXXX register --captcha '5fad97ac-7d06-4e44-b18a-b950b20148ff.challenge.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQn-Ay831RawVFnRyHrhusXnNVU82D6DoYiFsbA9a7oHNrANx-K5kC0xmdL1CRnrB8isEJd605ceBmjIgt4wf4sCQWyVpoPm5D3xIrvKrRYkrbr1Cav1bFUkj6WbBqyU28q3163r2RJmtA0dMBa8llWdtJkkKxh-85vv-PmMScQSUH7COpRbM0w6oxLjXmUiRSHWSaR__JybCuYt3sYzlE4tLnSu1UUFjSv9uHcFlR5VTyO0ejuPPDA-PEZtR93tvDeInHpu0YrJ74YXGGVf7Be6higbJ0cuU3Mg-bdpla2JQBkbU9uC0aBY6sSw2sijHrAbArF2EdNqJa7c6Lq5ICSSJrO9AXYZBbT31gF0Bg09p2TK9SA9z2mCox48YMowjUU22kgQDVGFyNxEF9aWSPttjY24vb8IzHIL-6kNo3aYDolWypiu-34gQjcvFrVM3EyaylYVm-hc0goPeXoKxkz7AJ6l0nXWpSkGVLneDrvGqghDClFBrEn5BxuoIVOO564Bo1QeI1ZUNGgEq5SWUyLaiDy_oPrOSKtwWOYkFjVsu1o_eW3OxuYdXHpObiypyA5YxBVyB4G8LUfLqXQza_UtniHB8QPGcS7qVH6VTRhQ5EzO4mjZ_7rAuMwyWXSMNU3akONa9ErCKw7ucShr9uxwlkuzyiqsdtH-fAE5REDPL9-q48wFovifVGSTQJzGzdREU_jIpMzKLitcq-PsvgCiz24mJh3Oz2pHtpOSgBEYp9HBuKrGkNpRBNGaKYbS26JrHcQYoNRsevNwDSxvxVhsOKZzVjnobEoQZgCoc2L40XT0-ECJ-Op87xV-fPd4MAjpkU0WbIVmJb30d2zsvOPaZOT0be8B6wgZWyJ-R0UWkRbZaFlRE-Gu3TIM8pOyPmvVLdtYA46W_h0smaNmUOX8qq3apXwl8-t_4U-jHwU0JahC4g7dL33PdZFhB5HhvcABxsIzDW6eFogdEKW5HyMfT5meM1_pJ5Y66JrYOE_vhfBzD-AaG9RBojs9i5Pi-OjaDbvTBZKlbTH5CB96rx-NzKnJlYZGRyKHiRfuB7eM86jhaoVLNuGa4Vjp97PTt4XxTb7B__g9ZcKlr3RQBmw2dZo0TIiJoJ8lIkZT_lOnseDKYf9hHla92rjzfyJ_2Og5mZanreBVRENJVGi7tT85aCHSCDINJRRWjdUCoaoxz-URIpgQpkAauLn6elBx0NqIENjjUPXR4jn1ZqMOKAIKrCCzQMhiIj6_II5cV6Lnk0aNkDSgBSQMVMhvBK0w3MgS-exmcc2aD2sPmEonHZ2XnjIxjsZdUrWXwxgIQXD6O7iVKIJVHChTqNwDoUoX3FGQcwuQZZdf3LNFwI1-99w04o__wZxZh5PQHhDfNgEVISAYuPP01Cl-GgpNUPWuYLeHnfySPo_kVFA4InfQk5KMrH3AdEnfXnvNPmLZP_fW6cM1xlvWr1-Baxwv9uaZuNNa0RM8SvLrHLAhP_FE93zr1-xbN7499jnoM0mDUWLSz4b-bC05rtVOlH-WSHGBYmsnRDGhGqqRB_Y66T7kOU_x1mJYhbo6cACXHTomQOO_jmeKOQL6L29VyhxS6vqDmNmtg2yVxzHMDJ07LrNkJumfoxly7fm4b7136kCd2W06JuEtDpFiZ_YA88Fqv2hTJeaZcQi3R9vWQ6xQTaL-mvE5Xb197AI0GXd6wuL0qqr5YcBzf_53m8VXgDqreKRUBrdAzGMDLrZ_Letcsr8XzeJQjP_4Y71Qtf85hI2A8U3yMVF-Ki9aOtknPeQkVG1a-gJJoepvWXareoGM9dng2KzzuTq0io_EFz84S0fk030_W3lp93cTIw8h3BPuiQ2kb4VY65rGkJYMTG8ipKNOvYf3H7nm7otHh4YzvhAasndFnXCRAyY-8t4sYNRli2hhKHzMKi-y0wJzdHlgXoFJE54G9FwIXWA45GFzn8cn3dqWX-fPk9lmh65EgJmPTiG6N0SorfzbsiCKbTL7WIC7PMjIE5WtYmJ46yWVOQeSwnZTMUYeS6tcfqbVuy49PUnT0KkKYSBM1yc1I155jTiyu8JgBg3U-QKgtQL1Wtw6Km4uyDCdR6S57MQps7tRMFfSKzAiEUVdI_bNgYJRwoNi3uUKfO6heQYMYDd_-fvhEF3vGCrWC12RjypuBuXqAlMZRJGkmvcFSmyRiA4f4dOi854KUFyxNWtDwuhLop9LgkjC1YoO35QKeCWTt9dM-rGD9EuzQtu0O-0QpXjFXK-oSSDwgj0_50bPWMuOIaySmYodIut3xCBEaXknWMzoTKMnl8GV3j0lHrAC6FoMblNHjILWtc2w3VKUEuHAmyJnuq2trMZatocLxyKsUBoxuhRHf4rjczFaR6IDh3WrmZC1s4ULeRKihRMKBj4F5WdQjyFGlplUxErrgQ2VRujtEyYda-2zVYnVCsdk2TdnqMoFIguzRZxbaPUatnjMAufgbmYPBcMxhxsfMVH--x869j_QRrDtIXwUoNYC2B78ezxNCPwhYMBYJrK6AetaCYZPSbSksVRmtmdH8R-OCuytA1TE4WzHyTkmmLK3AUjzCt6yO9fYrjJyjmzsSJi2ONeJ-yrU-OFvmgPheJQs-SLcowI6j-9ZrWMzct6vorKSzBTUp1iNfmdFbYg9e0xWU9pklgZspP54sY9oW078EzTMP-k37rhqU41-Yxh2cPrFaTVpN-OltybglW7OXcCvaB8G7fOdN1nwYO8t8Nva5I-COSCujlmqkJ8FlBOlDBvGibycuOnx3pNar9aVwg9CnrznfRDA0TBJjrwGoNHbtTmw-K6P5hW6_JIOfUT4eVbIYFEwBHy6GF9BqTj2xcQOLU6TJKD5ve9s0OQPLxudDxGZRGH4NtnZ8uC7udnCVV3Pz9-aIo5q5cyfZaNTzJpuirsrTe8dYn_50NvKBV_zIXvnEqixZT6g7ogtri2C_zRyb_QVuA1a7Z0S42oJu3t5XOk0i6siaJAXsFnRTqWWjiHz0YRUX5epwkFnUM8FQQ3M9xovUZXbmdXNDQnWOm54ujIvNauRHKJr1EVIsD5PvoBzdoYH9D0iu82o0SothdSsBh3czsRkza-4oFM14w_OTV6fggHOrbCCbHw8rXWVUgZV-d9rEkmeXYSEbMKsaFyEJBmXwyEkZQqn0xeHRC35UzSWBJeY5m46G23N-2AcjzynkuOKchemS7r8swOYkM5Wuz3g44_6nvR4ow1PWOQR2HYLOsAgRG5nsbaS_wvBzQxHIWsj8jADcTiJ9DtMsXQ8t9ISlgJc4YDmY3wqCNTQinD-ESJaypUM49kb3dPOl8_MsfpJ5UTEtahuq6lUXlPYdyjtNXi59pSmIm8diaclbT1Q3ztEG7BnixUuiRxwwgn1sgScJyBJVP8RzNHhVNTztwBd4ECjZXhwzmS8Imuoc2hhcmRfaWTOAzGDb6JwZAA.w3ekVqkTUI0oBQZphWHsaD0DDVE9i0X37uTXqGdncsA'

Invalid captcha given.

Any idea ?
