### ISSUE TITLE
RATE_LIMIT_FAILURE

### ISSUE THREAD

**Issue by Henner** [AsamK/signal-cli#1285]
Hi,

I am using signal-cli 0.11.11 and I am getting the following error by sending messages to new recipients:
{"results":[{"recipientAddress":{"uuid":"276f91b9-b3f2-4a68-85db-1d8670800c4c","number":"+49123456789"},"type":"RATE_LIMIT_FAILURE","token":"52bdb829-f0f2-4c93-925d-c5a5269c75e0","retryAfterSeconds":86400}],"timestamp":1689766360013}

We are sending Messages and attachments. But only 50 messages overall per week so far...

anybody an idea what to do? I wrote a message to signal support to ask for help or an offer, but did not get an answer.

**Comment by cuu508** [comment]
The exact criteria that Signal uses for rate limiting are not known – which makes sense, as otherwise users would game the limits.

I have an unproven theory that one criteria is the number of one-way messages from you to new recipients. If you regularly send messages to new recipients, and they do not respond back, you can see how this could look like a spammy behavior from Signal's point of view. My workaround for this is to ask recipients to send a reply message. I *think* this helps, but I do still hit rate limits from time to time.

The other thing I do is, if sending a Signal message hits a rate limit, my app falls back to sending an email instead, so that the message is not lost. The email says something along the lines of "we hit a rate limit while sending a Signal notification to you, so here is the same notification in email form instead".

When you do hit a rate limit, you have the option of solving a CAPTCHA, submitting the solved CAPTCHA to Signal, which will at least temporarily lift the rate limit.

Instructions for solving CAPTCHA: https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha#get-captcha-token

Submit the solved CAPTCHA with "signal-cli submitRateLimitChallenge": https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#submitratelimitchallenge

Signal currently uses the hCAPTCHA service. hCAPTCHA has a special accessibility mode which makes solving CAPTCHAs slightly less annoying: https://toot.lv/@cuu508/110741021091583988

My blog post about sending Signal notifications from a web application, where I discuss these same rate limiting issues as well: https://blog.healthchecks.io/2023/01/how-healthchecks-sends-signal-notifications/

**Comment by Henner** [comment]
Thanks for your reply!
I have tried:
signal-cli -a +498154711 register --captcha signalcaptcha://signal-hcaptcha......

but that did not change anything...
Did I do something wrong?

**Comment by cuu508** [comment]
@Henner `signal-cli  register --captcha ...` is how you pass in CAPTCHA token when registering a new account. 

If you are hitting a rate limit when sending a message try submitting the CAPTCHA token using the [`signal-cli submitRateLimitChallenge`](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#submitratelimitchallenge) command.
