### ISSUE TITLE
DBus - Self-sent messages

### ISSUE THREAD

**Issue by KRtekTM** [AsamK/signal-cli#136]
Hello everybody,

I'm trying to sent message to myself through dbus-send (which works well for other numbers) but there is no message received on dbus event (subscribed through qdbusviewer, another messages are received correctly).

My signal-cli instance is active (no slave device).

**Comment by AsamK** [comment]
Signal doesn't send self-sent messages to the sending instance. The sender already knows the message so it doesn't need to send it. Implementing that would also be non trivial, because it would need to store a separate session state for receiving self-sent messages.
In signal-cli self-sent messages are only sent to slave/master devices for synchronization.

**Comment by KRtekTM** [comment]
Thanks for your reply.
On Android Signal app, I'm sending messages back to myself on daily basis and in the conversation, there are both sent and received message.
Maybe it's some specific feature of Android app. Never mind :)

**Comment by AsamK** [comment]
Yeah, the Android app doesn't send anything (not even sync messages), it just stores it in the db as sent and received ;)
