### ISSUE TITLE
Failed to send message: Rate limit exceeded: 413

### ISSUE THREAD

**Issue by micah** [AsamK/signal-cli#161]
Hi,

I setup signal-cli, registered/verified a new phone number. I created a group and then sent some test messages to it, it seemed to work. I am using it to send an alert to people, it is just one message when it happens.

A week later I discovered the alert wasn't sent, so I went to investigate, and tried to send a message through signal-cli, but I got this:

Failed to send message: Rate limit exceeded: 413

Not sure why... I tried to re-register and verify, and do an updateAccount. But still I'm unable to send even a single small test message to one user.

Is there anyway to debug this?

**Comment by five-c-d** [comment]
There is an HTTP 413 code returned from signal-server when you are trying to register / re-register too many times in a day.  There is a (different) rate-limiting thing for when you are trying to send out too many messages too quickly, is my understanding, though I have never actually seen anybody hit that limit.  You were getting the 413 error when you were registered?  And then you were able to unregister, then re-register, the same phone number without getting any 413 error messages (or "unable to connect to server" errors) at all?  *After* which, you started getting 413 error-messages *again* when attempting to send messages?  

That sounds very strange.  How many linked device are there?   And are we sure you are in control of all of them, and none are running amok?  :-)   Do you have multiple sig-cli instances running, or multiple signal-clients of any sort perhaps, all possibly using different phone numbers but all connecting from the same IP or ISP, possibly?  Maybe that would trigger a 413 during groupchat-alert attempts, which was not triggered during one re-registration?  But it sounds like you *also* tried sending from your sig-cli to a single enduser manually, and got a 413 when doing that....

**Comment by micah** [comment]
Thanks for the response. I just found out that the problem seems to be
completely unrelated to any rate-limiting.

I made a group, with 3 numbers in it. The group worked fine. Then one of
the numbers changed their security number (me). Then when the messages
are sent to this group, this error happens. I didn't know it, but the
other members of the group *are* getting the messages, even though I see
that error.

I get the same message if I try to send directly to that one number.

I fixed it by doing a 'trust' on the number.

**Comment by five-c-d** [comment]
Interesting, so the problem was not that you were rate-limited, but that you needed to accept a safety-number-has-changed response from signal-server before you were able to continue encrypted conversations using the new pubkey / sessionkey.    

Possibly see also https://github.com/AsamK/signal-cli/issues/44#issuecomment-389544122 by @swedishjeff back in May 2018, who started seeing Rate limit exceeded 413 'errors' immediately after "reinstalling Signal for Desktop" ... not sure that would involve a change in the safety-number since it was only the linked-slave-device that was reinstalled, presumably?  

Once you <a href="https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#listidentities"changed the trust-status</a> that sig-cli listed for the 3rd person in your groupchat, suddenly you stopped getting HTTP 413 messages and started getting success.  Before doing that, whenever you tried to send a sig-cli message to the groupchat... which involves sending a message from sig-cli to person#A and another message to person#B and another message to person#C with their encryption-keys, you started getting 413 errors within sig-cli, **but** person#A and person#B received the messages, with only 'untrusted' person#C failing to get anything.  Similarly, if you just tried to directly message 'untrusted' person#C you *also* receive the HTTP 413 message.  

So it sounds like what is happening, is that sig-cli just keeps on retrying and retrying and *retrying*, until eventually signal-server assumes that sig-cli is a spammer!  Not good.  The fix is presumably for sig-cli to internally check whether the recipient of a 1-on-1 message is in fact 'trusted'-status already, prior to attempting to send.  Or alternatively, it can attempt to send once, but the **first** time the send in non-successful sig-cli ought to immediately look at the trust-levels, rather than just going into an infinite-loop of retrying (which only an HTTP 413 rate-limit-exceeded message from signal-server breaks out of).  This code *looks* like it tries to handle the case where a recipient is untrusted... but it must not be working?  https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Manager.java#L917-L948  

Or maybe, you do not have that code installed?  @micah , what version of AsamK/signal-cli are you using?  Are you making any custom changes to the code locally?

**Comment by micah** [comment]
> Interesting, so the problem was not that you were rate-limited, but
> that you needed to accept a safety-number-has-changed response from
> signal-server before you were able to continue encrypted conversations
> using the new pubkey / sessionkey.

It seems that is what happened.

> Once you <a
> href="https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#listidentities"changed
> the trust-status</a> that sig-cli listed for the 3rd person in your
> groupchat, suddenly you stopped getting HTTP 413 messages and started
> getting success.  Before doing that, whenever you tried to send a
> sig-cli message to the groupchat... which involves sending a message
> from sig-cli to person#A and another message to person#B and another
> message to person#C with their encryption-keys, you started getting
> 413 errors within sig-cli, **but** person#A and person#B received the
> messages, with only 'untrusted' person#C failing to get anything.
> Similarly, if you just tried to directly message 'untrusted' person#C
> you *also* receive the HTTP 413 message.

That is an accurate description of what I experienced.

> So it sounds like what is happening, is that sig-cli just keeps on
> retrying and retrying and *retrying*, until eventually signal-server
> assumes that sig-cli is a spammer!
>
> for sig-cli to internally check whether the recipient of a 1-on-1
> message is in fact 'trusted'-status already, prior to attempting to
> send.  Or alternatively, it can attempt to send once, but the
> **first** time the send in non-successful sig-cli ought to immediately
> look at the trust-levels, rather than just going into an infinite-loop
> of retrying (which only an HTTP 413 rate-limit-exceeded message from
> signal-server breaks out of).  This code *looks* like it tries to
> handle the case where a recipient is untrusted... but it must not be
> working?
> https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Manager.java#L917-L948

Or could it be that its not retrying and retrying, but signal servers
are providing this result code for trying to send to someone when their
key has changed like this?

> Or maybe, you do not have that code installed?  @micah , what version
> of AsamK/signal-cli are you using?  Are you making any custom changes
> to the code locally?

I have 0.6.0 installed.

**Comment by charlierlee** [comment]
I'm having this issue in certain group, but not in others. and in the group this is happening to, nobody gets the message from signal-cli.

**Comment by AetherUnbound** [comment]
I'm seeing this issue both while messaging in a certain group and while attempting to trust another person's safety number:
```
root@6f8229b6af77:/app# signal-cli -u $BOT_NUMBER trust -v "<redacted>" +<redacted>
org.whispersystems.signalservice.api.push.exceptions.RateLimitException: Rate limit exceeded: 413
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1444)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1434)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1419)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1357)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1351)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:495)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1643)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1618)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1466)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:598)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:387)
	at org.asamk.signal.manager.Manager.sendSyncMessage(Manager.java:1085)
	at org.asamk.signal.manager.Manager.sendVerifiedMessage(Manager.java:1926)
	at org.asamk.signal.manager.Manager.trustIdentityVerifiedSafetyNumber(Manager.java:1997)
	at org.asamk.signal.commands.TrustCommand.handleCommand(TrustCommand.java:69)
	at org.asamk.signal.Main.handleCommands(Main.java:184)
	at org.asamk.signal.Main.handleCommands(Main.java:135)
	at org.asamk.signal.Main.main(Main.java:65)
```

**Comment by AetherUnbound** [comment]
I was able to manually trust the numbers in the group that were previously raising errors about untusted devices, and the 413 errors I was seeing fairly consistently went away! I think the surmise that the CLI kept trying to send messages to those devices and reached the rate limit was correct.

**Comment by AsamK** [comment]
might have been caused by an issue in libsignal-service: https://github.com/signalapp/libsignal-service-java/commit/ebab1a7c06f428a5f5ba0c1fc36bb2ddac8e698a

**Comment by asad-awadia** [comment]
@five-c-d  what is the signal messaging rate limit?

**Comment by elkaz** [comment]
@SiderWinde did you find a workaround for this? I have exactly the same issue on signal-cli 0.11.6 with libsignal-client 0.21.1.

**Comment by SiderWinde** [comment]
I didn't find any solution I just persevered with testing until complete, waiting for Rate limit to expire (I left it 24 hours) each time I encountered it. In my use case scenario I won't need to register all the time. Have run into no rate limit issues with messages subsequently.

**Comment by SiderWinde** [comment]
@elkaz forgot to tag you, reply above.
