### ISSUE TITLE
Captcha registration 429

### ISSUE THREAD

**Issue by Light407** [AsamK/signal-cli#1631]
I just can't get through the captcha registration, I keep getting either "Invalid Captcha" or "Failed to register: StatusCode: 429 (RegistrationRetryException)".

In some tutorials it says that the prefix "signalcaptcha://" should not be included in the captcha to be passed into the command line, but the documentation says it should be there. I've tried both but can't get it to work.

In the Captcha documents it says "-u USERNAME" and in the main page "-a ACCOUNT" for register. I guess both USERNAME and ACCOUNT would be the full phone number but shall we use -u or -a.

Also saw that there are two different captcha links (registration or challenge), which one should work? Been trying both but just can't get past it and not sure what I am doing wrong.

The command I have is 

`signal-cli -u +4123456789 register --captcha 'captcha string'`

Appreciate any help!

**Comment by AsamK** [comment]
The signal server has rate limiting, so after too many attempts (including "Invalid captcha") it will return 429 errors, which can only be resolved by waiting.
"signalcaptcha://" prefix used be an issue but is now automatically stripped by signal-cli, so that's not the issue. "-u USERNAME" has been replace by "-a ACCOUNT", but both work the same.
The registration captcha link should be used. Make sure to do the signal-cli register and the captcha on the same IP address. Otherwise I can't say why the captcha is considered invalid.

Duplicate of #1545

**Comment by Light407** [comment]
Thanks for the reply @AsamK Really appreciate it! Will try again, thanks!

**Comment by old-square-eyes** [comment]
This is stupid. 2 attempts and I'm locked out with 429. I'm supposed to wait 24hours now?

signal-cli -a +12345 register --captcha "signal-hcaptcha.5fad97blahblah..." was what I used. What's wrong with that. Do you actually want people to adopt your platform?

Edit: Sorry I thought CLI was official - didn't realise it's 3rd party and I don't blame you for the error, I blame Signal.
