### ISSUE TITLE
Disappearing msgs disaster

### ISSUE THREAD

**Issue by posix4e** [AsamK/signal-cli#188]
Everytime I send a msg to my favorite signal group it resets the disappearing msgs settings. Happy to pay a few hundred bucks to get this fixed

**Comment by AsamK** [comment]
Sending disappearing messages already works, they just can't be configured with signal-cli directly.
You need to set the disappearing messages setting in the app and then run `signal-cli -u +XXX receive` so that signal-cli knows about the setting.
Then sending messages to that group will respect the disappearing messages setting.
