### ISSUE TITLE
usernames are stored in clear-text

### ISSUE THREAD

**Issue by philiparvidsson** [AsamK/signal-cli#189]
usernames should be one-way-hashed in the configuration file for security. this is a serious issue and should be fixed asap. when a message is received, the username should be hashed the same way and looked up in the config (through its hash).

**Comment by Trolldemorted** [comment]
Ah you mean the telephone number? I thought you were talking about the name of a user (since signal-cli prints both).

Nevertheless, a program that can execute code as your user (and thus read your config) can also manipulate the binaries you execute, so I don't think there is a reasonable security boundary here.

**Comment by philiparvidsson** [comment]
yes. 

not sure I agree. in the case where someone is able to recover disk contents from a seized disk, it will be easy to find out which phone numbers the owner had contact with. these phone nos could be easily linked to real persons, who could give then reveal the identity of the owner.
