### ISSUE TITLE
signal-cli returns EXIT_SUCCESS even when message failed to send

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#22]
I've been using my https://github.com/kb100/signal-authenticator as a send-only device. Today it just stopped working for no apparent reason. I checked my authenticator code and it shows that signal-cli is returning success when sending a message, but I never receive the message. Just for the heck of it, I tried `signal-cli -u USERNAME receive` and used grep to count that I had exactly 99 pending messages ("Got receipt.", all from the same number).

The fact that it was 99 seems too suspicious to be coincidence. I don't know exactly how signal works, but I wonder if this could have anything to do with the fact that there are 100 preKey records in my config.

After doing the `signal-clii -u USERNAME receive` my authenticator started working again.

I would hope that if `signal-cli` can tell that a message failed, then it would not return EXIT_SUCCESS so at the very least my authenticator can account for it.

**Comment by Trolldemorted** [comment]
I am not yet that much into the signal protocol, but i think this could be not that easy.

my first thoughts:

- a username may be associated to several devices, and every message is sent to every device, and each of them may fail individually
- the signal protocol may rely on your cli instance to receive receipts in order to [keep up the ephemeral keys](https://whispersystems.org/blog/advanced-ratcheting)

**Comment by AsamK** [comment]
Good point about the exit code, signal-cli already exits with a non-zero code in some failure cases, but not all. I'll change it to always return a non-zero code if sending to at least one recipient failed. However that won't catch problems when delivery failed or the recipient can't decrypt the message.
