### ISSUE TITLE
Discrepancy between attachment id and filenames

### ISSUE THREAD

**Issue by ra-rock** [AsamK/signal-cli#226]
Hi!

I noticed in the JSON output, attachment id's almost, but not quite, correspond to the filename of the attachment saved into the signal-cli folder. Bellow I'm adding 3 examples. On an aside, what is the `filename` field for, if it doesn't correspond to a file in the filesystem?

Filename: `$HOME/.local/share/signal-cli/attachments/4049077375952874625`
JSON:
```
    ...
    "attachments": [
          {
            "contentType": "image/jpeg",
            "filename": "signal-2019-09-23-195001.jpeg",
            "id": 4049077375952874500,
            "size": 388361
          }
        ]
    ...
```
Filename: `$HOME/.local/share/signal-cli/attachments/5340856775153064702`
JSON:
```
    ...
    "attachments": [
          {
            "contentType": "image/jpeg",
            "filename": "signal-2019-09-23-194715.jpeg",
            "id": 5340856775153065000,
            "size": 388361
          }
        ]
    ...
```
Filename: `$HOME/.local/share/signal-cli/attachments/891719212540873262`
JSON:
```
    ...
    "attachments": [
          {
            "contentType": "image/jpeg",
            "filename": "signal-2019-09-23-194627.jpeg",
            "id": 891719212540873200,
            "size": 388361
          }
        ]
    ...
```

**Comment by AsamK** [comment]
oh boy, ...
looks like the jackson json library is converting the id (which is a 64bit integer) to a double float value when serializing to json... That means the value gets rounded and doesn't match the original id anymore.
I guess we need to store the `id` as a json string to prevent the rounding.

The filename is included in the attachment message, it's the original filename from the sending device. signal-cli doesn't use it for the received file, because it's not guaranteed to be unique
