### ISSUE TITLE
left groups stay in groupstore

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#23]
title says it all, i just quit a group, signal-cli did not complain, but the group is still there.

**Comment by AsamK** [comment]
That's intentional, the group info is not removed from the groupstore, only your own number is removed from the list of recipients. That's also in line with what Signal-Android and Signal-Desktop do, they still show the group title after having left a group.
The handling of left groups could probably be improved to prevent sending to groups you're no longer a member of.

**Comment by Trolldemorted** [comment]
thanks for your clarification, preventing sending to groups is reasonable imo.
