### ISSUE TITLE
receiving messages triggers group updates

### ISSUE THREAD

**Issue by rensbaardman** [AsamK/signal-cli#267]
**Situation**
- I have two devices for an identity: one for `signal-cli` and one for Signal Desktop (macOS)
- I had never used `receive` on the `signal-cli`, but have used the Desktop app for individual and group chats

**Problem**
The first time I use `receive` with `signal-cli`, it receives all messages etc. But then suddenly I get a lot of notifications on the Desktop app with 'Group updated'. This happened with 3 of the 4 groups I'm in, and ranges from 5 to 23 'Group updated'-notifications. These are visible to all group members, but only when they use the Desktop App, not on the mobile app (at least not on iOS).

I am not sure if this is a problem with Signal Desktop, but nevertheless, I had assumed that using `receive` would not in any way modify or update any conversations or groups.

Can anyone reproduce this, or can give anyone some pointers into further debugging this? (to find out whether the problem lies with `signal-cli` or the Desktop App?)

**Comment by Trolldemorted** [comment]
Receiving causes group updates if your signal-cli device doesn't know the group. Any time a group message belonging to an unknown group is received, signal-cli will send a group info request to the sender, which will respond with a group update.

**Comment by rensbaardman** [comment]
Ah, thanks for the quick explanation.

But then, you would expect only 1 update per group, right? And why is this shown in the Desktop App?

**Comment by Trolldemorted** [comment]
Messages are received (more or less) in order, so if there is more than one incoming message from an unknown group in the queue, signal-cli will send a group info request for every of those messages. The group update responses will be added to the end of the incoming queue, so they will be processed after the batch of messages which trigger one info request each.

Signal-Android itself does not display that it sent an info request response, but it does sync them to all slave decides. Signal-Desktop then displays it, because it received a synced group update.

**Comment by rensbaardman** [comment]
Thanks again for taking the time to write this clear explanation :)

If you don't mind, one last question: why do _others_ also see the 'Group Update' notification (in Signal Desktop)? Shouldn't this happen solely on _my_ side?

**Comment by Trolldemorted** [comment]
If you are the one using signal-cli, you are sending out info requests, their mobile devices are responding with group updates, and those group updates are synced to their slave devices!

If you open an issue at Signal-Android's repository they might stop syncing those messages, in my opinion syncing them never made any sense.
