### ISSUE TITLE
[question] link: not a valid qr code for link

### ISSUE THREAD

**Issue by aanno** [AsamK/signal-cli#277]
I tried to link to my existing signal account the way it is described in 

* https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning) and
* https://mark.benschop.me/blog/?p=122

However, my android phone always says 'not a valid qr code' on scanning the resulting qr code.
Any suggestions?

**Comment by aanno** [comment]
Well, in contrast to the blog entry, my has different structure:

* URI from current master: tsdevice:/?uuid=BNj_YoA2E3MsxTmTtQvJSw&pub_key=BWpoUXmlzL4qhYCNmnI4U8OQ9Qmlj3aLN1kAc11NOjYi
* URI from blog entry: tsdevice:/21456y3egfsd7gwqogthgpo98ug===98fsfdagsdafgpfsdig97t2y3bfd

The result from encoding 'my' URI seems to be a much 'smaller' qrcode...

**Comment by AsamK** [comment]
You're URL format is correct, I don't know where the format from the blog entry comes from.
So the problem is probably with the created qr code, when using `qrencode`, you need to make sure to correctly escape the parameter to generate the correct qr code.

With this command it should work:
```sh
qrencode "tsdevice:/?uuid=BNj_YoA2E3MsxTmTtQvJSw&pub_key=BWpoUXmlzL4qhYCNmnI4U8OQ9Qmlj3aLN1kAc11NOjYi" -o qrcode.png
```
Or pipe it directly into an image view, like `feh`:
```sh
qrencode "tsdevice:/?uuid=BNj_YoA2E3MsxTmTtQvJSw&pub_key=BWpoUXmlzL4qhYCNmnI4U8OQ9Qmlj3aLN1kAc11NOjYi" -o - | feh -
```

**Comment by aanno** [comment]
Yes, you are right: I stumbled upon the missing quotes. Sorry for the noise. BTW, your signal-cli is gorgeous!
