### ISSUE TITLE
Signal certificate not trusted behind proxy

### ISSUE THREAD

**Issue by Sharelison** [AsamK/signal-cli#299]
Whenever I try to register behind a proxy, I get a ssl handshake error:

```
$ export _JAVA_OPTIONS="-Dhttps.proxyHost=myproxy.com -Dhttps.proxyPort=7878"
$ signal-cli -u +<phonenumber> register

Request verify error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: 
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid 
certification path to requested target

```
If I try this without a proxy (no _JAVA_OPTIONS set) I'm getting: Request verify error: java.net.SocketTimeoutException: connect timed out

Is there a particular CA that I should import first? If so, which one?

**Comment by AsamK** [comment]
What proxy are you using? Is it doing some sort of man in the middle inspection?
The signal servers have their own self-signed certificate, of which the CA is hardcoded in libsignal-service.
So I think as long as the proxy just passes through the https stream it should work.

**Comment by numericOverflow** [comment]
I am running into this same issue, but have some additional info so resurrecting this issue.  

```
Failed to register: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (SSLHandshakeException)
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am behind a corporate firewall/proxy that does MITM inspection.  Obviously, this will cause SSL issues as in general, anything MITM is frowned upon from a privacy standpoint, but in this case its the "good guys"™ doing it.  Is there a way to override the cert to allow the corp MITM to connections occur?

I would **** *____never____* **** want to do this in a private situation because it undermines the assumptions of privacy, but for a work scenario where the MITM is required and I'm OK with it for governance, can this be done?

--- 

I've tried a couple things so far:
1) Extracting the trusted CA's from a windows machine, then adding them to the JVM's CA keystore, but that didn't work.  (JAVA_HOME\lib\security\cacerts).  

   I used `certutil` to extract the certs, and `keystore` tool import to the above `cacerts` store.

   This *should* have the MITM CA, but can't see exactly which CA is used, so can't be sure, but seems not to help at all.  Got same errors as above prior to modifying cacerts store.


2) Next I tried replacing the whisper.store with the cacerts I built out above (which should have MITM root certs) as suggested [here](https://github.com/AsamK/signal-cli/issues/1067#issuecomment-1295204655) when the certs got updated to backport to older versions, but I get a new error

```
2024-08-13T09:16:03.326-0500 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR
not set, falling back to temp dir
2024-08-13T09:16:03.348-0500 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.5
2024-08-13T09:16:03.721-0500 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
2024-08-13T09:16:04.119-0500 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2024-08-13T09:16:04.296-0500 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@50fe837a
2024-08-13T09:16:04.298-0500 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
Error loading or creating state file: java.io.IOException: Wrong version of key store. (AssertionError)
```

   I'm assuming this might be due to the fact that the cert is hardcoded somewhere to stop MITMs.
   
Thoughts?? I'm hitting my wall of knowledge/options without some suggestions.
