### ISSUE TITLE
signal-cli link - Link request error: null

### ISSUE THREAD

**Issue by mnzaki** [AsamK/signal-cli#322]
I am using the latest release of Signal (4.63.2) and latest release of signal-cli (0.6.8) and when I try to link signal-cli to my Android 10 device I get a `Link request error: null`

How do I turn on more debugging output? what other info can I provide?

**Comment by AsamK** [comment]
That's probably already fixed in master (4177deccf1e91483f54c5fcfacffce0ce525ad39).
Linking should have worked regardless of the error message, it just didn't print the success message.
Can you check if receiving messages works and if the data file `~/.local/share/signal-cli/data/+PHONE_NUMBER` exists?
