### ISSUE TITLE
Failed to decrypt

### ISSUE THREAD

**Issue by maxcountryman** [AsamK/signal-cli#586]
Hello, I'm seeing an error message periodically that looks something like this:

org.whispersystems.libsignal.InvalidMessageException: Message from [redacted]:2 failed to decrypt; sender ratchet public key [redacted] message counter 4\\nCandidate session 0 failed with \'invalid ciphertext message\', had 1 receiver chains\\nReceiver chain with sender ratchet public key [redacted] chain key index 0\

I don't see any direct examples of this elsewhere and would be curious to understand what's going on.

**Comment by AsamK** [comment]
Haven't seen that one before ...
Looks like a broken or out of sync session.

**Comment by kunturapu** [comment]
Hello AsamK.
First of all, I want to thank you for making this possible.

I am having the same issue. I cant synchronize my contacts from .local/share/signal-cli/data/mynumber with the Signal-Desktop.
Im on Ubuntu 20.04 LTS, 64bit.
I do not use a smartphone. So I try to do all manually set-up my contact-list into Signal.
I do not use any other messenger.
Atm I do not see any contacs in my Desktop, because there is an error after editing the data-file.
I start the daemon in the terminal, while Signal-Desktop is open.
Then I go to Settings/Import Contacts in the app...nothing happens:  then this happens in the terminal:

`Envelope from: +49xxxx (device: 2)
Timestamp: 161xxxx (2021-04-08T15:16:38.585Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: Message from +49xxxx:2 failed to decrypt; sender ratchet public key 0320411226ab37756xxxxxxx message counter 10
Candidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains (ProtocolInvalidMessageException)
Failed to decrypt message.

Envelope from: +49xxx (device: 2)
Timestamp: 161xxxx (2021-04-08T15:16:38.585Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: Message from +49xxxx:2 failed to decrypt; sender ratchet public key 0320411226ab37756xxxxxxx message counter 11
Candidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains (ProtocolInvalidMessageException)
Failed to decrypt message.

Envelope from: +49xxxx(device: 2)
Timestamp: 161xxxx(2021-04-08T15:16:38.585Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: Message from +49xxxx:2 failed to decrypt; sender ratchet public key 0320411226ab37756xxxxxmessage counter 12
Candidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains (ProtocolInvalidMessageException)
Failed to decrypt message.

Envelope from: +49xx(device: 2)
Timestamp: 161xxxx(2021-04-08T15:16:39.478Z)
Exception: org.whispersystems.libsignal.InvalidMessageException: Message from +49xxxx2 failed to decrypt; sender ratchet public key 0320411226ab37756xxxxxmessage counter 13
Candidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains (ProtocolInvalidMessageException)
Failed to decrypt message.
`
I anonymized my data.
Why does it appear 4 times?
What can I do?

Thank you!
kuntur

**Comment by maxcountryman** [comment]
@kunturapu I'm going to close this issue--I've moved on to `[signald](https://gitlab.com/signald/signald)` which so far is much more reliable.
