### ISSUE TITLE
GitHub actions to build working binaries

### ISSUE THREAD

**Issue by wayneworkman** [AsamK/signal-cli#677]
Hello,

I've had difficulty getting 0.8.5 working on Debian 10, getting this error:
`Missing required native library dependency: libsignal-client`

I've tried compiling the dependencies, but they fail to build. I'm not a java expert, I tried googling the errors and haven't been able to figure it out.

Though I did find this repo: https://github.com/exquo/signal-libs-build
The builds there _work for me_ out of the box.

**The ask:** - What's this other guy doing differently, and can that be integrated into this repo's release builds? His work is licensed GNU GPL v3, so all of it could be used.

**Comment by exquo** [comment]
Hello from this other guy :)

@AsamK if you'd like to integrate the rust libs builds into this repo, I'd be happy to help. 

There's some reason to keep them separate though: the signal-cli project produces the Java code to interface with the signal service; making sure its dependencies work on every platform may be outside of its scope.

**Comment by AsamK** [comment]
It would be nice to provide signal-cli binaries here, that run directly on all major platforms. Preferably triggered automatically when a new tag is pushed and without too much additional code that needs to be maintained.

However I currently don't have time for adapting and maintaining the build code.

And anyway thanks @exquo for providing your signal builds!

**Comment by exquo** [comment]
Sure!

If you're interested, I can make a PR with the required changes to package the compiled libraries into signal-cli in this repo.

I was planning to split my build code into the 'compile libs' and the 'repackage signal' parts, and to make separate releases for each version of each of the rust libraries, as well as for signal-cli. This way if the required version of a dependent library does not change between signal-cli releases, the script can download the build from an existing release without having to recompile it. That would also be neater than having all the files for the libs and for signal-cli together in a long list in single release assets. And it allows to check for new versions of the libs in libsignal-service-java, before they make it into signal-cli as requirements.

Just mentioning this because for this repo just the 'repackage signal' workflow can be used, assuming the rust libs are already compiled somewhere. That 'somewhere' can be another repo (to not clutter this one with rust libs releases) - either my current one mentioned above, or a new one can be made. There the libs can be compiled for all the architectures, including the non-major ones. 

An alternative to that option is to compile the rust libs as a part of a build workflow in this repo, and keep them as workflow artifacts rather than include them into a release. The downside is being more wasteful (because I'll need to compile them all anyway, and because they'll always be recompiled here for new signal-cli releases, even if the dependencies versions don't change) and more error prone (in case a new version of one of the dependencies fails to compile for whatever reason; keeping that process separate gives some cushion to fix it).

Let me know what your thoughts on this are!

**Comment by AsamK** [comment]
Yes, that would be cool.
I think I'd prefer to keep the lib builds in a separate repo and just add the repackaging to the signal-cli workflow.
You can just use your repo for now, but maybe it would make sense to move the repo to my namespace when merging the workflow.

**Comment by exquo** [comment]
Sounds good! I'll make a PR once I convert the workflow to in-repo building.

**Comment by bublath** [comment]
I was also experimenting a bit with packaging.  I have a Debian package to install signal-cli as Dbus Service on my Raspberry PI.

I added it to my fork as an example (without the bin and lib contents unter /opt/signal)
https://github.com/bublath/signal-cli/tree/master/signal-cli_0.9.0-1_armhf
The .deb package can be created with
dpkg-deb --build --root-owner-group signal-cli_0.9.0-1_armhf

I wonder if something like this could be automated along with the efforts described above. It of course would also require the two binary .so libraries for arm7l

**Comment by exquo** [comment]
Update: libsignal-client v0.10.0 includes in it the zkgroup library. Also the [releases page](https://github.com/signalapp/libsignal-client/releases/tag/v0.10.0) provide the built files: `libsignal_jni.so`, `.dylib` and `.dll`.

> In addition, the Java builds on Sonatype have an additional "testable" artifact that includes macOS and Windows builds of libsignal_jni in addition to the usual Linux build, so that signal-client-java can be used for testing on all three of Signal's desktop platforms.
> https://github.com/signalapp/libsignal-client/releases/tag/v0.10.0

Their file sizes seem to be too large though.. Maybe some android dependencies are bundled in?


As for the main issue in this thread (automatically packaging the compiled libraries into signal-cli releases), there's now a separate "re-package binaries into signal-cli" [workflow](https://github.com/exquo/signal-libs-build/blob/a6130852313269d6c67ac301c734588c57480de2/.github/workflows/package-signal-cli.yaml) that can be adapted into this repo build workflow. I should have some time to do that in not too distant future, sorry it's been taking a while! Using the upstream-built binaries in this process is also an option.
