### ISSUE TITLE
JSON I/O event loop

### ISSUE THREAD

**Issue by kbin76** [AsamK/signal-cli#87]
Hi,
i've been looking into scripting signal (like making bots), but haven't found any perl or python bindings for the java library. Writing perl bindings for java seemed overwhelming for me. Also I only noted later that someone else already had started some JSON output formatting stuff, so I started off fresh on hacking together a JSON API for signal-cli. 

It's works as a form of event loop where you can post JSON requests to stdin for sending messages and it spits out JSON blobs of received messages on stdout. The API works asynchronously given the nature of the underlying message system. 

Currently only send and receive messages operations are implemented. Other operations you need to carry out using normal signal-cli commands. It's quite convenient that you can combine signal-cli command line with scripting, that way you don't need to implement all those functions in the script (like register/verify indentity that you only do once). Also it's neat to take advantage of the .config storage of signal state (trusts etc).

The fork is here:
https://github.com/kbin76/signal-cli

I've patched Main.java to implement jsonevtloop command and then created simple Perl module for interact with it as proof of concept under perl/.

Plz let me know what you think!

BR
Kalle

**Comment by AsamK** [comment]
Nice work. I've just pushed my own json output format to master, so you can use that too (8717665d1d273a32afef136c15c0d5abaaae0f85)

A few suggestions:
* use the jackson json library instead of gson, no need for multiple json libraries in signal-cli
* Could be implemented as a parameter to the `daemon` command (`daemon --dbus`)

**Comment by a1ad** [comment]
AsemK, 
Can you elaborate how to receive messages in json format?
Thanks

**Comment by AsamK** [comment]
@a1ad I've updated the man page: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#receive
Just add the `--json` paramter to the receive command: `signal-cli receive --json`

**Comment by kbin76** [comment]
I'll change to jackson lib instead... I started before there were any json in master and also i'm no java programmer so not sure what libs are popular etc, just grabbed one...

I'll try and take your json output and remove mine since it was a kludge anyway, but keep the json ingestion of "requests" and also try to move some stuff to have parameters enable starting as "daemon" but in json-mode as you suggested.

One other thing that I haven't been able to figure out is when you send messages, how do you later map the receipts received to a particular sent message? Is it possible to retrieve some kind of unique message-id upon send that later is present in the receipt?  I haven't studied the innards of the underlying signal-api, but this functionlity would be highly useful in order to provide async callback behaviour in scripting wrappers such as the perl-one I've put together (also planning on python one later on).

**Comment by kbin76** [comment]
But come to think of it, is daemon-mode really the proper way to call this mode of operation?  It's not going fork and lie in the background (as daemon suggests), but rather stay in "foreground" spitting json stuff out on stdout and ingesting json requests on stdin...?

also appoligies if this is not the right place to discuss development stuff... plz redirect me to where one would do this if not here... :-)

**Comment by thefinn93** [comment]
Just wanted to let you guys know this looks really exciting. I've been spending a *ton* of time messing around with DBus, this jsonevtloop makes it much easier. I slapped together a simple bot framework to use it, if anyone is interested, it can be found [here](https://github.com/JankySolutions/SignalBotFramework). Would love see this happen, please let me know if I can help.

**Comment by skorokithakis** [comment]
Could this be merged in? I tried to implement a simple Python library that can send-receive, but there's no way to do this currently if you aren't using DBus, since signal-cli locks the config files and you can't `send` while a `receive` command is running.

It's a pity that we can't currently implement bidirectionai daemons without DBus, since DBus is pretty fiddly to set up (and I can't even get it working on my machine).

**Comment by thefinn93** [comment]
@skorokithakis Since this was sitting with no sign of merging, I went off and built my own. It's called signald, [you can find it here](https://gitlab.com/thefinn93/signald). It's similar to signal-cli but all functionality is exposed via a unix domain socket instead of the command line. I've successfully written python-based Signal bots with it.

**Comment by skorokithakis** [comment]
@thefinn93 That looks fantastic, thank you. Do you have some sample Python code to share? Also, would it be possible to use this over a TCP socket? Lastly, do you have a prebuilt jar for those of us who don't have a Java toolchain installed?

**Comment by thefinn93** [comment]
We cleared most of this up out of band, but for others reading along: there's a (crappy) python library and prebuilt jars (and debs), and there are no plans to allow connecting to signald via a TCP socket.

**Comment by AsamK** [comment]
I've now implemented a json API based on JSON-RPC for signal-cli, see #679
