### ISSUE TITLE
JSON data is sometimes corrupted

### ISSUE THREAD

**Issue by ivan** [AsamK/signal-cli#89]
I am running signal-cli 0.5.5, and after a few dozen reboots, I saw this on boot:

```
Jun 19 23:36:11 ra systemd[1]: Starting signal-cli daemon...
Jun 19 23:36:12 ra signal-cli[1522]: Error loading state file "/var/lib/signal-cli/data/+[NUMBER]": Unexpected character (',' (code 44)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
Jun 19 23:36:12 ra signal-cli[1522]:  at [Source: sun.nio.ch.ChannelInputStream@704a52ec; line: 1, column: 2]
Jun 19 23:36:12 ra systemd[1]: signal-cli.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 19 23:36:12 ra systemd[1]: Failed to start signal-cli daemon.
```

`/var/lib/signal-cli/data/+[NUMBER]` consisted of:

```
,
  "threadStore" : {
    "threads" : [ ]
  }
}{
  "username" : "+[NUMBER]",
  "deviceId" : 1,
...
  },
  "groupStore" : {
    "groups" : [ ]
  },
  "contactStore" : {
    "contacts" : [ ]
  },
  "threadStore" : {
    "threads" : [ ]
  }
}
```

and was otherwise fine after I removed the spurious `threadStore` from the top of the file.

If some commit after 0.5.5 might have fixed this, sorry, please close.

The other thing I should mention: this happened after I started using signal-cli over dbus to send a message every hour.

**Comment by AsamK** [comment]
Hm, this looks like an issue with an interrupted save or filesystem corruption after an unclean shutdown. signal-cli always writes out the complete json with the Jackson ObjectMapper

**Comment by ivan** [comment]
I was running XFS on a recent 4.4 LTS kernel, did a clean shutdown, and I haven't seen anything else go haywire.

Thanks for the pointer, though, I'll just reopen if I see this again or find a way to reproduce it.

**Comment by fbrausse** [comment]
Hi, working on [scli](https://github.com/fbrausse/scli), I found the same issue, which occurs quite often (very annoying, I'm up to device_id: 7 now for my one development machine) and not always in a way allowing to restore the JSON file. Filesystem is xfs, linux-5.1.15. `scli` is started in an own `dbus-run-session` (to have multiple running for development) and in turn starts a `signal-cli -u NUMBER daemon --json` instance, which in the original non-forked [scli](https://github.com/isamert/scli) gets killed with SIGKILL (now I'm sending SIGTERM first).

It hasn't occurred again since I passed `true` to `fileChannel.force()` instead of `false` here: https://github.com/AsamK/signal-cli/blob/78474453d7de5fa50c32c460e18877485bc26f78/src/main/java/org/asamk/signal/storage/SignalAccount.java#L210 I'll report back when I'm more sure. A cleaner solution might be to save the `account` in a `ShutdownHook`, especially while `daemon` mode has no method to shut it down orderly, but even then - to be sure.

All in all, I suppose this issue would be alleviated by not starting a new `signal-cli` for every account, but it would still require the single daemon instance to be shut down orderly.

**Comment by fbrausse** [comment]
OK, I investigated further and found out about the following:
- SignalAccount's `.load()` and `.save()` pass a `Channels.new{Input,Output}Stream(fileChannel)` to the JSON reader/writer.
- The JSON reader/writer closes it's input: https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L989-L993 and output: https://github.com/FasterXML/jackson-databind/blob/1ee322231b3e6b9c1815f692e2d9ed9fb3a8e9ad/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1674
- the Java documentation says that closing the streams obtained by `Channels.new{Input,Output}Stream(fileChannel)` will close the underlying FileChannel.

Piecing this together, I wrapped the I/OStreams in another class and gave that to the JSON de/serializer. But the corrupted data still remained. Not being sure what to do, I wrapped the whole de-/serialization into `synchronized (fileChannel) {}` such that `.load()` and `.save()` now operate with exclusive access. Since then no more corruption. :)

All in all, this is the change: https://github.com/fbrausse/signal-cli/commit/65cbb50b0eae269577f98c11aeeb0e0af4d36b13.
