### ISSUE TITLE
pre-keys-pni folder grew to unmanageable size

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#960]
after several years of continuously using this (awesome! :rocket:) project, my local folder grew to a huge and unmanageable size.

specifically, the problem is traced back to the `pre-key-pni` folder:
```
# full path
$ cd ~/.local/share/signal-cli/data/*.d/pre-keys-pni

# huge folder
$ du -sh .
6.6G	.

# lots of files
$ find . -type f | wc -l
1719100
```

is this a symptom of some kind of cleanup bug?
or am I supposed to be maintaining my profile folder somehow?

**Comment by AsamK** [comment]
Sorry, that's a bug in the current version. It creates new PNI pre keys at every startup but never uploads them to the Signal server ... I've already fixed it in the master branch (ce7aeb02bc152e12e4c2bf26a0bfd81ec289def7).
Due to this specific bug you can completely delete the pre-keys-pni folder as a workaround.
